---
title: "Create map figure"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---

This code creates a figure that (a) illustrates the geographical distribution of big team leadership and participation rates in psychology, and (b) examines links between those rates and indicators of economic wealth (GDP)

# Setup
```{r include= F}
# specify data directory
data_dir <- Sys.getenv("data_dir")

# source setup file
source('setup.R')
```

# Prepare OpenAlex data
## Open and isolate OpenAlex authorship data
```{r open.alex, include = F}
DF.author <- 
  # open data
  readRDS(file.path(data_dir,
                    "openalex",
                    "btpsych24a_data_bib_processed.Rds")) %>% 
  
  # isolate big team science records
  filter(size.bin != "1 - 4",
         size.bin != "5 - 9")

# focus on author listsx`
DF.author <- DF.author$author
```

## Prepare for parallel processing
```{r}
# detect number of cores and create a cluster
num_cores <- 50  # Leave three cores free
cl <- makeCluster(num_cores)

# export variables needed for parallel processing
clusterExport(cl, 
              varlist = c("DF.author"))


# loadlibraries needed
clusterEvalQ(cl, 
             {library('tidyverse')
               library('tidygeocoder')}
             )

```

## Geocode records
```{r}
DF.geo <- 
  # isolate affiliation information
  parLapply(X = DF.author,
            cl = cl,
            function(sublist)
              c(sublist['institution_display_name'],
                sublist['institution_country_code'])
            )
# select only instances with full affiliation information
## changed to *any insatance* on Jul 28 2025 following reviewer recommendation
### this drops number of records from 49919 to 41107
DF.geo <- DF.geo %>% 
  Filter(function(sublist) any(!is.na(unlist(sublist))), .)

# cluster export DF.geo
clusterExport(cl, 
              varlist = c("DF.geo"))
  
  # geocode using institution name and country
DF.geo2 <- DF.geo %>% 
  parLapply(X = .,
            cl = cl,
            function(sublist)
              as_tibble(sublist) %>% 
              
              mutate(address = paste0(institution_display_name,
                                      ", ",
                                      institution_country_code)
                     ) %>% 
              
              geocode(.,
                      address = address,
                      method = 'arcgis', 
                      lat = latitude, 
                      long = longitude
                      )
            )

# save geocoded list
saveRDS(DF.geo2,
        file.path(data_dir,
                  "location",
                  'btpsych24a_geocode.Rds')
        )
```
