---
title: "Create map figure"
output: word_document
editor_options: 
  chunk_output_type: console
---

# Setup
```{r setup, include= F}
# specify data directory
data_dir <- Sys.getenv("data_dir")

# source setup file
source("setup.R")
```

```{r}
# open processed OpenAlex data
DF.o <-
  readRDS(file.path(data_dir, "openalex", "btpsych24a_data_bib_processed.Rds"))

# identify country of first author via safe extraction
DF.o$author1.country <-
  lapply(seq_len(nrow(DF.o)), function(i) {
    tryCatch(
      DF.o[i, ][["author"]][[1]][["institution_country_code"]][[1]],
      error = function(e) {
        NA
      }
    )
  })

# Prepare for merging: convert to iso3 codes
DF.o <- DF.o %>%
  mutate(
    iso3 = as.character(author1.country),
    iso3 = if_else(iso3 == "NA", NA_character_, iso3),
    iso3 = countrycode(iso3, origin = "iso2c", destination = "iso3c")
  )
```

## Combine with weird indicators
```{r}
# open weird data
DF.w <-
  readRDS(file.path(
    data_dir,
    "worlddata",
    "btpsych24a_weird.Rds"
  ))

# for simplicity, calculate average 'ride' scores for each country
DF.w <- DF.w %>%
  group_by(iso3) %>%
  summarise(
    r = mean(r, na.rm = T),
    i = mean(i, na.rm = T),
    d = mean(d, na.rm = T),
    e = mean(e, na.rm = T)
  )

# left join with DF
DF.o.w <-
  left_join(DF.o, DF.w, by = "iso3")

# export
saveRDS(
  DF.o.w,
  file = file.path(
    data_dir,
    "worlddata",
    "DF.o.w.Rds"
  )
)

# reload
DF.o.w <- readRDS(
  file = file.path(
    data_dir,
    "worlddata",
    "DF.o.w.Rds"
  )
)

# prepare population data
DF.pop <-
  read.csv(
    file.path(
      data_dir,
      "worlddata",
      "population",
      "btpsych24a_worlddata_pop.csv"
    ),
    skip = 4
  )

# process population data
DF.pop <- DF.pop %>%
  filter(Country.Name != "Not classified") %>%
  rowwise() %>%
  mutate(pop = mean(X2000:X2024, na.rm = T)) %>%
  ungroup() %>%
  select(Country.Code, pop)

# prepare merge with other indicators
DF.w2 <- DF.w %>%
  group_by(iso3) %>%
  summarise(
    r = mean(r, na.rm = T),
    i = mean(i, na.rm = T),
    d = mean(d, na.rm = T),
    e = mean(e, na.rm = T)
  )

tmp <- DF.pop %>%
  rename("iso3" = "Country.Code") %>%
  left_join(DF.w2, by = "iso3")

# export
saveRDS(
  tmp,
  file = file.path(
    data_dir,
    "worlddata",
    "tmp.Rds"
  )
)

tmp <-
  readRDS(
    file = file.path(
      data_dir,
      "worlddata",
      "tmp.Rds"
    )
  )
```

# Create plots comparing distribution across different bands of big team science
Create general plotting function
```{r}
DataViz2 <- function(outcome, label, adjust = 1) {
  ggplot(
    data = DF.o.w,
    aes(x = .data[[outcome]])
  ) +

    # size.bin == '1 - 4'
    geom_density(
      data = DF.o.w %>%
        filter(size.bin == "1 - 4"),
      color = "#1b9e77",
      adjust = adjust,
      alpha = 0.4
    ) +

    # size.bin == '5 - 9'
    geom_density(
      data = DF.o.w %>%
        filter(size.bin == "5 - 9"),
      color = "#d95f02",
      adjust = adjust,
      alpha = 0.4
    ) +

    # author.n > 10
    geom_density(
      data = DF.o.w %>%
        filter(authors.n > 10),
      color = "#7570b3",
      adjust = adjust,
      alpha = 0.4
    ) +

    # actual distribution
    geom_density(
      data = tmp,
      aes(weight = pop),
      linetype = "dotted",
      adjust = adjust,
      alpha = 0.4
    ) +

    # fix aes
    xlab(label) +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.y = element_blank()
    )
}
```

## Create plots
```{r}
r.fig <-
  DataViz2(
    outcome = "r",
    label = "GDP Per Capita (Millions)",
    adjust = 5
  )

i.fig <-
  DataViz2(
    outcome = "i",
    label = "Industry-Based GDP (%)",
    adjust = 5
  )

d.fig <-
  DataViz2(
    outcome = "d",
    label = "Democracy Index",
    adjust = 5
  )

e.fig <-
  DataViz2(
    outcome = "e",
    label = "Secondary School Enrollment (% Gross)",
    adjust = 5
  )

base_plot <-
  plot_grid(
    r.fig,
    i.fig,
    d.fig,
    e.fig
  )

# delete vestigial
rm(r.fig, i.fig, d.fig, e.fig)
```

## Create custom legend
```{r}
legend_levels <-
  c(
    "1st Author Affiliation (< 5 Co-Authors)",
    "1st Author Affiliation (5 - 9 Co-Authors)",
    "1st Author Affiliation (10+ Co-Authors)",
    "Global Distribution"
  )

# Create a dummy df with 2 points per group so geom_line can create lines with the appropriate aesthetics
legend_df <- data.frame(
  group = factor(rep(legend_levels, each = 2), levels = legend_levels),
  x = rep(c(1, 2), times = length(legend_levels)),
  y = rep(seq_along(legend_levels), each = 2)
)

# Define color mapping
my_colors <- c(
  "1st Author Affiliation (< 5 Co-Authors)" = "#1b9e77",
  "1st Author Affiliation (5 - 9 Co-Authors)" = "#d95f02",
  "1st Author Affiliation (10+ Co-Authors)" = "#7570b3",
  "Global Distribution" = "black"
)

# Define linetype mapping
my_linetypes <- c(
  "1st Author Affiliation (< 5 Co-Authors)" = "solid",
  "1st Author Affiliation (5 - 9 Co-Authors)" = "solid",
  "1st Author Affiliation (10+ Co-Authors)" = "solid",
  "Global Distribution" = "dotted"
)

# 2. Build dummy plot mapping aesthetics at top-level

# Create a dummy ggplot with the appropriate graph aesthetics to extract a legend
dummy_plot <-
  ggplot(
    legend_df, # dummy data frame with 2 observations per group
    aes(
      x = x,
      y = y,
      color = group,
      linetype = group
    )
  ) +
  geom_line(linewidth = 1.2) +
  scale_color_manual(
    # Choose the appropriate colors and labels
    name = "Legend",
    values = my_colors,
    labels = legend_levels
  ) +
  scale_linetype_manual(
    # Choose the appropriate linetypes and labels
    name = "Legend",
    values = my_linetypes,
    labels = legend_levels
  ) +
  guides(
    color = guide_legend(
      title = NULL,
      direction = "horizontal",
      nrow = 2,
      override.aes = list(linetype = c("solid", "solid", "solid", "dotted"))
    ),
    linetype = "none"
  ) +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 9)
  )

# Extract the guide-box from the dummy plot, and remove any zeroGrob[NULL] elements to get the legend
all_guides <-
  cowplot:::get_plot_component(dummy_plot, "guide-box", return_all = TRUE)

legend <- all_guides[[which(!sapply(all_guides, inherits, "zeroGrob"))]]
rm(all_guides)

# Combine the legend extracted from the dummy plot to the base figure
legend_plot <-
  plot_grid(base_plot, legend, nrow = 2, rel_heights = c(1, 0.2))

# delete vestigial
rm(
  base_plot,
  legend,
  legend_levels,
  legend_df,
  dummy_plot,
  my_colors,
  my_linetypes,
  DataViz2
)
```

# Globe panel: geocode, prep, plot, and merge with legend panel
## Prepare data
```{r}
# Prepare OpenAlex big-team author data for geocoding
DF.author <-
  DF.o.w %>%
  filter(size.bin != "1 - 4", size.bin != "5 - 9")

DF.author <- DF.author$author

# Geocode records (skip if already saved)
geo_path <-
  file.path(data_dir, "location", "btpsych24a_geocode.Rds")

if (!file.exists(geo_path)) {
  DF.geo <-
    lapply(DF.author, function(sublist) {
      c(
        sublist["institution_display_name"],
        sublist["institution_country_code"]
      )
    }) %>%

    Filter(
      function(sublist) {
        any(!is.na(unlist(sublist)))
      },
      .
    ) %>%

    lapply(function(sublist) {
      as_tibble(sublist) %>%
        mutate(
          address = paste0(
            institution_display_name,
            ", ",
            institution_country_code
          )
        ) %>%

        tidygeocoder::geocode(
          .,
          address = address,
          method = "arcgis",
          lat = latitude,
          long = longitude
        )
    })
  saveRDS(DF.geo, geo_path)
} else {
  DF.geo <- readRDS(geo_path)
}

# Identify leaders and supporters
DF.geo <- lapply(DF.geo, function(sublist) {
  sublist %>%
    mutate(
      leader_coun = .[["institution_country_code"]][1],
      leader_lat = .[["latitude"]][1],
      leader_lon = .[["longitude"]][1],
      supporter_coun = .[["institution_country_code"]],
      supporter_lat = .[["latitude"]],
      supporter_lon = .[["longitude"]]
    )
})

# Prepare map data
DF.map <- lapply(DF.geo, function(sublist) {
  slice(sublist, -1)
}) %>%
  bind_rows() %>%
  select(leader_coun:supporter_lon) %>%
  filter(
    paste0(leader_lat, ", ", leader_lon) !=
      paste0(supporter_lat, ", ", supporter_lon)
  ) %>%
  filter(!is.na(supporter_lat), !is.na(leader_lat)) %>%
  mutate(
    leader.region = countrycode(
      .$leader_coun,
      origin = "iso2c",
      destination = "region"
    ),
    supporter.region = countrycode(
      .$supporter_coun,
      origin = "iso2c",
      destination = "region"
    )
  )

# manual fixes
DF.map[
  !is.na(DF.map$leader_coun) &
    DF.map$leader_coun == "RE",
]$leader.region <- "Sub-Saharan Africa"

DF.map[
  !is.na(DF.map$supporter_coun) &
    DF.map$supporter_coun == "RE",
]$supporter.region <- "Sub-Saharan Africa"

DF.map[
  !is.na(DF.map$leader_coun) &
    DF.map$leader_coun == "XK",
]$leader.region <- "Europe & Central Asia"

DF.map[
  !is.na(DF.map$supporter_coun) &
    DF.map$supporter_coun == "XK",
]$supporter.region <- "Europe & Central Asia"

# transform coordinates to crs 4326 then to ESRI:54030
supporter.coord <- DF.map %>%
  select(supporter.region, supporter_lat, supporter_lon) %>%
  st_as_sf(
    coords = c("supporter_lon", "supporter_lat"),
    crs = 4326,
    remove = F
  ) %>%
  st_transform(crs = "ESRI:54030") %>%
  mutate(
    supporter_lat_new = st_coordinates(.)[, 2],
    supporter_lon_new = st_coordinates(.)[, 1]
  )
leader.coord <- DF.map %>%
  select(leader.region, leader_lat, leader_lon) %>%
  st_as_sf(
    coords = c("leader_lon", "leader_lat"),
    crs = 4326,
    remove = F
  ) %>%
  st_transform(crs = "ESRI:54030") %>%
  mutate(
    leader_lat_new = st_coordinates(.)[, 2],
    leader_lon_new = st_coordinates(.)[, 1]
  )

DF.map <- cbind(supporter.coord, leader.coord)
rm(supporter.coord, leader.coord)
```

## Create globe figure
```{r globe_panel}
# Globe figure
world <- ne_countries(scale = "medium", returnclass = "sf")

globe.fig <- ggplot() +
  # plot map layer

  layer_spatial(data = world, color = NA) +
  # change coordinate projections

  coord_sf(crs = "ESRI:54030") +
  # add dots for supporters
  geom_point(
    data = DF.map %>%
      filter(!is.na(leader.region), !is.na(supporter.region)),
    aes(
      x = supporter_lon_new,
      y = supporter_lat_new,
      colour = supporter.region
    ),
    size = .4,
    alpha = .01
  ) +
  # connect leaders and supporters
  geom_curve(
    data = DF.map %>% filter(!is.na(leader.region), !is.na(supporter.region)),
    aes(
      x = leader_lon_new,
      y = leader_lat_new,
      xend = supporter_lon_new,
      yend = supporter_lat_new,
      colour = leader.region
    ),
    curvature = -0.5,
    size = 0.1,
    alpha = .01,
    show.legend = F
  ) +
  # improve aesthetics
  cowplot::theme_minimal_grid() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.justification = "center",
    panel.grid.major = element_line(size = .3)
  ) +
  guides(
    color = guide_legend(override.aes = list(size = 3, alpha = 1), nrow = 2)
  ) +
  labs(x = NULL, y = NULL)
```

## Combine globe and plots
```{r}
# Combine globe and gdp figures
final.fig <- plot_grid(
  globe.fig,
  NULL,
  legend_plot,
  nrow = 3,
  rel_heights = c(4.5, 0.5, 5),
  labels = c("A", "B", "")
)
```
