---
title: "Create files for checking the reliability of contributorship coding"
author: "Anonymized for peer review (NC)"
reviewer: "Anonymized for peer review (JT)"
output: word_document
editor_options: 
  chunk_output_type: console
---

This code creates a spreadsheet for checking the reliability of contributorship coding and examines the Intraclass Correlation Coefficient of coding by JT and GG

```{r}
# load libaries
source("setup.R")

# specify data directory
data_dir <- Sys.getenv("data_dir")

# open and process data
DF.c <-
  # open data
  read.csv(
    file.path(data_dir, 'contributorship', 'btpsych24a_cont_coding.csv'),
    na.string = "N/A"
  ) %>%

  # filter
  filter(
    #remove instances without contributorship statements
    !is.na(contributorship.statement),
    contributorship.statement != "",

    # remove instances where coders recommended removal
    remove.revise != 1,

    # remove instances where there wasn't anything to code
    !(is.na(conception) &
      is.na(execution) &
      is.na(analysis) &
      is.na(draft.writing) &
      is.na(review.writing) &
      is.na(funding)),

    # remove instances where G coded
    Coder == "J"
  ) %>%

  # randomly select 20 cases
  slice_sample(n = 20) %>%

  # clear data
  mutate(
    contributorship.statement = "",
    conception = "",
    execution = "",
    analysis = "",
    draft.writing = "",
    review.writing = "",
    funding = "",
    Coder = "G"
  )
```

Export
```{r}
# if file doesn't exist (it should), create it
if (
  !file.exists(file.path(
    data_dir,
    'contributorship',
    'btpsych24a_cont_coding_rel.csv'
  ))
) {
  write.csv(
    DF.c,
    file.path(data_dir, 'contributorship', 'btpsych24a_cont_coding_rel.csv'),
    row.names = F
  )
}
```

# GG manually coded the 20 entries and saved them in btpsych24a_cont_coding_rel.csv

# Open and process coded contributorship data
```{r}
# recoded records from GG
DF.g <-
  read.csv(
    file.path(data_dir, 'contributorship', 'btpsych24a_cont_coding_rel.csv'),
    na.string = "N/A"
  ) %>%

  # select relevant variables
  select(id, conception:draft.writing, Coder)

# original coded records
DF.j <-
  read.csv(
    file.path(data_dir, 'contributorship', 'btpsych24a_cont_coding.csv'),
    na.string = "N/A"
  ) %>%

  # select relevant variables
  select(id, conception:draft.writing, Coder) %>%

  # semi join (focusing only on records that have been recoded by GG)
  semi_join(y = DF.g, by = 'id')

# bind files
DF.rel <- rbind(DF.g, DF.j) %>%

  # pivot data for processing
  pivot_longer(conception:draft.writing) %>%

  # count number of authors who have contributed to each category
  mutate(
    # if N/A leave blank, otherwise count number of commas and add 1
    n = if_else(
      is.na(value),
      NA,

      # otherwise, count number of commas and add 1
      str_count(value, ",") + 1
    )
  ) %>%

  select(-value) %>%

  # pivot
  pivot_wider(names_from = Coder, values_from = n) %>%
  arrange(G)
```

# Examine reliability
```{r}
ICC(
  DF.rel  %>%
    select(G, J)
)
```


